#!/usr/bin/env bash
set -e
HWVERSION="6.0.2"
SERIALS="$HOME/.scripts/segger_sn.txt"

if [ "$#" -lt 3 ]; then
	echo "Usage: $0 <device> <segger> <fw> [hw version]"
	echo "device: brm|brx|mch"
	echo "segger: Segger serial index"
	echo "fw: Firmware to load"
	echo "hw version: Hardware version of device"
	exit
fi

GITROOT=`git rev-parse --show-toplevel`
if [ -z "$GITROOT" ]; then
	echo "Not in a git repo, aborting"
	exit 1
fi

FWV6JTAG="$GITROOT/geosatis/fw6_jtag.py"

if [ ! -f $FWV6JTAG ]; then
	echo "Cannot find $FWV6JTAG"
	exit 1
fi

DEVICE="$1"
if  [ "$DEVICE" != "mch" ] && [ "$DEVICE" != "brx" ] && [ "$DEVICE" != "brm" ]; then
	echo "Unknown device $1"
	exit 1
fi

FW="$3"

if [ "$#" -ge 4 ]; then
	HWVERSION="$4"
fi

SERIALIDX=`expr $2 + 1`
SN=`sed "${SERIALIDX}q;d" $SERIALS`
if [ "$SN" == "" ]; then
	echo "Cannot find segger serial number"
	exit 1
fi

$FWV6JTAG -u $SN $FW -b $DEVICE --hw $HWVERSION
