#!/usr/bin/env python3
import sys
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import argparse
import numpy as np

def plotCsv(csv):
    print(csv)

    df = pd.read_csv(str(csv), delimiter=',', header=0)

    df['AvgCurrent'] = df['Current'].rolling(10).mean()

    #df['Time'] = df['Time'].sub(df['Time'].iloc[0])
    #df['Mean'] = df['Pressure'].rolling(int(sys.argv[2])).mean()
    #df['Diff'] = (df['Mean'].diff()/5).rolling(int(sys.argv[3])).mean()

    print (df)

    fig, ax1 = plt.subplots()
    plt.xlabel('Time')

    line_voltage = ax1.plot(df['Time'], df['Voltage'], '-b')
    ax1.set_ylabel('[mV]')

    ax2 = ax1.twinx()
    #ax2.set_ylabel('[mbar/s]')
    line_current = ax2.plot(df['Time'], df['Current'], '-g')
    line_avgcurrent = ax2.plot(df['Time'], df['AvgCurrent'], '-m')
    line_level = ax2.plot(df['Time'], df['Level'], '-r')

    #line_speed = ax2.plot(df['Time'], df['Diff'], '-r')

    blue_patch = mpatches.Patch(color='blue', label='Voltage')
    green_patch = mpatches.Patch(color='green', label='Current')
    red_patch = mpatches.Patch(color='red', label='Level')
    magenta_patch = mpatches.Patch(color='magenta', label='AvgCurrent')
    plt.legend(handles=[blue_patch, green_patch,red_patch, magenta_patch])

    # Control time display
    start, end = ax1.get_xlim()
    ax1.xaxis.set_ticks(np.arange(start, end, 500))
    # Control Voltage axis
    ax1.yaxis.set_ticks(np.arange(0, 10000, 1000))

    plt.gcf().autofmt_xdate()

    plt.show()

if __name__ == '__main__':
    parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter,
            description='Plot data provided through a CSV file')
    parser.add_argument('csv',
                    help = 'CSV file containing the data to plot')
    args = parser.parse_args()
    plotCsv(args.csv)
