#!/usr/bin/env bash
# Sets up the code workspace layout
# Parameters:
# 1: workspace number to setup
if [ $# -eq 0 ]; then
	echo "Missing workspace number"
	exit
fi

i3-msg 'workspace number '"$1"''
i3-msg 'split v'
gnome-terminal
i3-msg 'layout tabbed'
sleep 0.2
cd $HOME/gitrepo/fwv6-main
vimx
#i3-msg 
