#!/usr/bin/env bash
#USERNAME="leo"
WALTERNAS="//192.168.1.10"
MNT_DIR="$HOME/mnt"
shares=(Shared Download Multimedia)

for share in ${shares[@]}; do
	LOCAL_DIR=$MNT_DIR/$share
	REMOTE_DIR=$WALTERNAS/$share
	if mount | grep $LOCAL_DIR > /dev/null; then
		echo "$LOCAL_DIR already mounted"
	else
		echo "Mounting $REMOTE_DIR to $LOCAL_DIR"
		sudo mount -t cifs -o username=$USERNAME $REMOTE_DIR $LOCAL_DIR
	fi
done
