#!/usr/bin/bash
# Reset MCU
sn0=260103290
sn1=260108510
if [ -z "$1" ]; then
	sn=$sn0
else
	if [ "$1" == "0" ]; then
		sn=$sn0
	elif [ "$1" == "1" ]; then
		sn=$sn1
	fi
fi

JLinkSTM32 -SelectEmuBySN $sn
