#!/usr/bin/bash
# Reset MCU
set -e

if [ "$#" -ne 1 ]; then
	echo "Usage: reset_mcu <sn index>"
	exit
fi

serialfile="$HOME/.scripts/segger_sn.txt"
serialidx=`expr $1 + 1`
sn=`sed "${serialidx}q;d" $serialfile`
if [ "$sn" == "" ]; then
	echo "Cannot find segger serial number"
	exit
fi

JLinkSTM32 -SelectEmuBySN $sn
