#!/bin/bash
# Any subsequent(*) commands which fail will cause the shell script to exit immediately
set -e

if [ -z "${ZEPHYR_BASE}" ]; then
	. src-zephyr
fi

serialfile="$HOME/.scripts/segger_sn.txt"
if [ "$#" -ne 2 ]; then
	echo "Usage: segflash <brm|brx|mch|rbr> <0|1>"
	exit
fi

if  [ "$1" == "mch" ] || [ "$1" == "brx" ] || [ "$1" == "rbr" ]; then
	mcu=STM32L4A6RG
elif [ "$1" == "brm" ]; then
	mcu=STM32L4A6VG
else
	echo "Arg1 should be brm, brx, mch or rbr"
	exit
fi

serialidx=`expr $2 + 1`
sn=`sed "${serialidx}q;d" $serialfile`
if [ "$sn" == "" ]; then
	echo "Cannot find segger serial number"
	exit
fi

LOG="$HOME/logs/segger/log_`date +"%Y-%m-%d_%H-%M-%S"`.log"
nbcores=`cat /proc/cpuinfo | awk '/^processor/{print $3}' | wc -l`
make -j${nbcores}
JLinkExe -log $LOG -device $mcu -if SWD -speed 4000 -SelectEmuBySN $sn -CommanderScript ~/.scripts/load.txt
