#!/usr/bin/bash
reporoot=`git rev-parse --show-toplevel 2>/dev/null`
if [ "$reporoot" = "" ]; then
	echo "$PWD not a git repo"
else
	if [ "$1" = "0.10" ] || [ "$1" = "0.10.0" ] || [ "$1" = "" ]; then
		rm -f $HOME/.zephyrrc
		cp $HOME/.zephyrrc_SDK_0_10_0 $HOME/.zephyrrc
	elif [ "$1" = "0.9.5" ]; then
		rm -f $HOME/.zephyrrc
		cp $HOME/.zephyrrc_SDK_0_9_5 $HOME/.zephyrrc
	fi

	zephyrenv=$reporoot/zephyr-env.sh
	if [ ! -f $zephyrenv ]; then
		echo "$zephyrenv doesn't exist, not a zephyr repo"
	else
		. $reporoot/zephyr-env.sh
	fi

	echo "ZEPHYR_BASE: $ZEPHYR_BASE"
	echo "ZEPHYR_SDK_INSTALL_DIR: $ZEPHYR_SDK_INSTALL_DIR"
fi


